services:
  - type: web
    name: anime-recommendation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_PwBW9tDI8afm@ep-old-silence-a2cqq1bg-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require